#!/usr/bin/env python3
import os

from glob import glob
from importlib import import_module
from inspect import cleandoc, getmembers, isfunction, signature


def uncapitalize(s):
    if len(s) > 0:
        s = s[0].lower() + s[1:]
    return s


def get_markdown(module):
    intro = cleandoc(module.__doc__)

    blocks = [intro]
    functions = [(k, v) for k, v in vars(module).items() if isfunction(v)]

    for i, (name, func) in enumerate(functions, start=1):
        definition = f"{i}. Apresente um definição da função `{name}{signature(func)}` que "
        doc = cleandoc(func.__doc__)
        [fst, snd] = doc.split(">>>", maxsplit=1)
        definition += uncapitalize(fst) + '```python\n>>>' + snd + '\n```'

        blocks.append(definition)

    return '\n\n'.join(blocks)


def main():
    os.makedirs("output", exist_ok=True)

    for file in glob("*.py"):
        module = import_module(file[:-3])
        with open(f"output/{file[:-3]}.md", "w") as md:
            markdown = get_markdown(module)
            md.write(markdown)


if __name__ == '__main__':
    main()
